[package]
name = "muggingface"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.3.1"
hf-hub = { version = "0.3.2", features = ["tokio"] }
shuttle-actix-web = "0.48.0"
shuttle-runtime = "0.48.0"
tokio = "1.26.0"
tracing = "0.1.40"

[build]
assets = [
  "static/*",
]
