[package]
name = "muggingface"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.3.1"
hf-hub = { version = "0.3.2", features = ["tokio"] }
shuttle-actix-web = "0.53.0"
shuttle-runtime = "0.53.0"
tokio = "1.26.0"
tracing = "0.1.40"
reqwest = { version = "0.12", features = ["json"] }
bip_metainfo = "0.12.0"
url = "2.5.4"
librqbit = { git = "https://github.com/djmango/rqbit.git", package = "librqbit" }

[build]
assets = [
  "static/*",
]
